### ISSUE TITLE
enclitlics double

### ISSUE THREAD

**Issue by Glottotopia** [fmatter/cldflex#1]
For the attached input XML file, enclitics are outputted twice in both the vernacular line (=da,=peyang) and the gloss line (=NOM,=COM). 

```
ause=da=da	llɨg	kälsre=peyang=peyang
...
old woman=NOM=NOM	boy	small=COM=COM
```

Expected: 
```
ause=da	llɨg	kälsre=peyang
old woman=NOM	boy	small=COM
```

In the XML file, we find two instances of "da", but only one "NOM" in uppercase, suggesting that indeed certain fields are outputted twice.
```xml
<morph type="enclitic" guid="d7f713e1-e8cf-11d3-9764-00c04f186933">
   <item type="txt" lang="kit">=da</item>
   <item type="cf" lang="kit">=da</item>
   <item type="gls" lang="en">=NOM</item>
   <item type="msa" lang="en">nominal enclitic</item>
</morph>
<item type="gls" lang="en">nom</item>
<item type="pos" lang="en">nominal enclitic</item>
```

[test.xml.txt](https://github.com/fmatter/cldflex/files/13267071/test.xml.txt)

**Comment by Glottotopia** [comment]
Github does not accept XML attachment, so I renamed the file to txt

**Comment by fmatter** [comment]
It appears that I had already come across & fixed this (in the dev version). Update to the newest version and it should work. Note: the command is now `cldflex corpus`, not `cldflex flex2csv`.
